name: Polygon Pull Request Verification

on: [pull_request]

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies and setup environment
      run: |
        python -m pip install --upgrade pip
    - name: Run the script
      run: |
        python3 scripts/land_claims_lint.py
